### ISSUE TITLE
[SetValue] Bug report @luizedu9 from gitter

### ISSUE THREAD

**Issue by Wilson08** [totvs/tir#393]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by luizedu9** [comment]
### Describe the bug
SetValue não está funcionando nos campos do tipo "Select". Após dar SetValue o campo não é preenchido após chamar o LoadGrid(). Outras tentativas de primeiramente abrir o campo para depois chamar o SetValue resultou em travamento do campo, não sendo possível prosseguir sem intervenção manual.

![image](https://user-images.githubusercontent.com/39964043/92927951-cc293f80-f414-11ea-9080-8a46c02fa829.png)

### To Reproduce
Foi utilizado no exemplo a seguir o MATA010, Cadastro de Produtos, que utiliza o formato de Grid "moderno". Mas também foi identificado o mesmo problema no MATA410, Pedido de Venda, no campo "Rateio" que utiliza o Grid "antigo".

Case 1:
self.oHelper.SetValue("Entra MRP", "N - Nao", grid=True, check_value=False) OU self.oHelper.SetValue("Entra MRP", "N", grid=True, check_value=False)
self.oHelper.LoadGrid()

Observação: Campo não é preenchido.
Terminal:
Filling grid field: Entra MRP
Waiting for container to be active
Waiting for container to be active
Waiting for container to be active ...

Case 2:
self.oHelper.SetFocus("Entra MRP", grid_cell=True)
self.oHelper.SetValue("Entra MRP", "N - Nao", grid=True, check_value=False) OU self.oHelper.SetValue("Entra MRP", "N", grid=True, check_value=False)
self.oHelper.LoadGrid()

Observação: É aberto a caixa do campo, mas ela fica presa e não continua. Tentei usar SetFocus novamente com SetKey ESC ou Enter, mas em nenhuma das tentativas foi possível fechar a caixa do campo. 
Se fechar o campo manualmente (clique, ENTER, ENTER), o LoadGrid volta no campo e o preenche corretamente.

![image](https://user-images.githubusercontent.com/39964043/92927377-e57dbc00-f413-11ea-8374-f314a9d84d02.png)


### Expected behavior
É esperado que o SetValue preencha o campo corretamente sem a utilização do SetFocus ou, na necessidade de utilizar o SetFocus, seja possível sair do campo.

### Desktop:

OS: Windows 10
Browser: Firefox
Version: 80.0.1 (64-bit)

**Comment by Wilson08** [comment]
Luiz, qual a versão do SmartClient WebApp ?

**Comment by luizedu9** [comment]
20-07-14-P12_SMARTCLIENT_WEBAPP_4.6.3_WINDOWS_X64_191205P

**Comment by Wilson08** [comment]
@luizedu9, estamos nos esforçando para identificar do que se trata o problema reportado. Como citado nos casos anteriores o problema indicado parece ser geral afetando diversos tipos de grid em diversas rotinas.
Realizando alguns teste com os scripts que temos no repositório de exemplos não conseguimos reproduzir o erro.

Poderia por favor realizar o seguinte teste:

- Atualizar o TIR para a ultima versão "1.17.1"

- Vou deixar em anexo na issue um arquivo chamado scripts.zip que vai conter duas pastas "MATA010" e "CTBA102" nessas pastas criamos alguns exemplos bem simples para tentar reproduzir o problema da issue, vamos precisar que execute esses scripts e nos envie o resultado (pasta log gerada ao final da execução do script com arquivo .csv e imagem em caso de erro).

- Scripts
[scripts.zip](https://github.com/totvs/tir/files/5234233/scripts.zip)

**Comment by luizedu9** [comment]
Estava na versão 1.16.18. Com a atualização para a 1.17.1 o funcionamento voltou ao normal. Pensei que já tinha atualizado.

Obrigado pelo suporte @Wilson08.
